import { Command } from 'commander';
import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import { raiseCliError } from '../lib/agent-contract.js';
import { spin } from '../lib/spinner.js';
import { isJson, isQuiet } from '../lib/cli-context.js';
import { loadConfigSafe } from '../lib/load-config.js';

// ─── FieldType → TypeScript type mapping ───

const FIELD_TYPE_MAP: Record<string, string> = {
  string: 'string',
  text: 'string',
  number: 'number',
  boolean: 'boolean',
  datetime: 'string',
  json: 'unknown',
};

// ─── System fields added to every table ───

const SYSTEM_FIELDS = [
  '  /** System-generated unique ID */',
  '  id: string;',
  '  /** ISO 8601 creation timestamp */',
  '  createdAt: string;',
  '  /** ISO 8601 last-update timestamp */',
  '  updatedAt: string;',
];

// ─── Config types (subset for typegen) ───

interface SchemaField {
  type: string;
  required?: boolean;
  references?: string | { table: string };
  enum?: string[];
}

interface TableConfig {
  schema?: Record<string, SchemaField | false>;
}

interface DbBlock {
  tables?: Record<string, TableConfig>;
}

interface ParsedConfig {
  databases?: Record<string, DbBlock>;
}

// ─── Config loading ───

const FULL_CONFIG_EVAL = { allowRegexFallback: false } as const;

/**
 * Resolve the config path. Checks for edgebase.config.ts and edgebase.config.js.
 */
function resolveConfigPath(cwd: string): string | null {
  for (const name of ['edgebase.config.ts', 'edgebase.config.js']) {
    const p = path.join(cwd, name);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

/**
 * Typegen must fully evaluate edgebase.config.ts so invalid legacy syntax
 * fails loudly instead of being silently dropped by regex fallback.
 */
function loadConfig(configPath: string, cwd: string): ParsedConfig {
  return loadConfigSafe(configPath, cwd, FULL_CONFIG_EVAL) as ParsedConfig;
}

// ─── Type Generation ───

function toPascalCase(s: string): string {
  const parts = splitIdentifierParts(s);
  if (parts.length === 0) return 'Table';
  const normalized = [...parts];
  normalized[normalized.length - 1] = singularizeWord(normalized[normalized.length - 1]);
  return normalized
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function splitIdentifierParts(value: string): string[] {
  return value
    .split(/[^A-Za-z0-9]+/)
    .flatMap((part) => part.split(/(?=[A-Z][a-z])|(?<=[a-z0-9])(?=[A-Z])/))
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => part.toLowerCase());
}

function singularizeWord(word: string): string {
  if (word.length <= 3) return word;
  if (/(ss|us|is)$/.test(word)) return word;
  if (/ies$/.test(word)) return `${word.slice(0, -3)}y`;
  if (/(xes|zes|ches|shes|ses)$/.test(word)) return word.slice(0, -2);
  if (word.endsWith('s')) return word.slice(0, -1);
  return word;
}

function isTsIdentifier(name: string): boolean {
  return /^[$A-Z_a-z][$\w]*$/.test(name);
}

function renderPropertyName(name: string): string {
  return isTsIdentifier(name) ? name : JSON.stringify(name);
}

function getReferenceLabel(reference: SchemaField['references']): string | null {
  if (!reference) return null;
  if (typeof reference === 'string') return reference;
  if (typeof reference.table === 'string' && reference.table.length > 0) return reference.table;
  return null;
}

function generateInterface(name: string, config: TableConfig): string {
  const typeName = toPascalCase(name);
  const lines: string[] = [];
  lines.push(`/** Table: ${name} */`);
  lines.push(`export interface ${typeName} {`);
  lines.push(...SYSTEM_FIELDS);

  if (config.schema) {
    for (const [fieldName, fieldDef] of Object.entries(config.schema)) {
      if (fieldDef === false) continue;
      const tsType = FIELD_TYPE_MAP[fieldDef.type] ?? 'unknown';
      const optional = fieldDef.required ? '' : '?';
      const referenceLabel = getReferenceLabel(fieldDef.references);
      const refComment = referenceLabel ? ` // references → ${referenceLabel}` : '';
      const enumComment = fieldDef.enum ? ` // enum: ${fieldDef.enum.join(' | ')}` : '';
      lines.push(`  ${renderPropertyName(fieldName)}${optional}: ${tsType};${refComment}${enumComment}`);
    }
  }

  lines.push(`}`);
  return lines.join('\n');
}

/**
 * Generate full type definitions file from a parsed config.
 * Supports the canonical `databases` block.
 */
export function generateTypes(config: ParsedConfig): string {
  const lines: string[] = [
    '// ─────────────────────────────────────────────',
    '// Auto-generated by `npx edgebase typegen`',
    '// Do not edit manually.',
    `// Generated at: ${new Date().toISOString()}`,
    '// ─────────────────────────────────────────────',
    '',
  ];

  // Collect all tables from the databases block
  const allTables: Record<string, TableConfig> = {};

  if (config.databases) {
    for (const dbBlock of Object.values(config.databases)) {
      for (const [tableName, tableConfig] of Object.entries(dbBlock.tables ?? {})) {
        allTables[tableName] = tableConfig;
      }
    }
  }

  if (Object.keys(allTables).length === 0) {
    lines.push('// No tables found in config.');
    return lines.join('\n');
  }

  for (const [name, tableConfig] of Object.entries(allTables)) {
    lines.push(generateInterface(name, tableConfig));
    lines.push('');
  }

  // Type map
  lines.push('/** Table name → Type mapping */');
  lines.push('export interface EdgeBaseTables {');
  for (const name of Object.keys(allTables)) {
    const typeName = toPascalCase(name);
    lines.push(`  ${renderPropertyName(name)}: ${typeName};`);
  }
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ─── Command ───

export const typegenCommand = new Command('typegen')
  .alias('tg')
  .description('Generate TypeScript types from edgebase.config.ts schema')
  .option('-o, --output <path>', 'Output file path', 'edgebase.d.ts')
  .action((options: { output: string }) => {
    const cwd = process.cwd();
    const configPath = resolveConfigPath(cwd);

    if (!configPath) {
      raiseCliError({
        code: 'typegen_config_not_found',
        message: 'edgebase.config.ts not found.',
        hint: 'Run `npx edgebase init` to create a project first.',
      });
    }

    const s = spin(`Reading config: ${path.basename(configPath)}`);

    let config: ParsedConfig;
    try {
      config = loadConfig(configPath, cwd);
    } catch (err) {
      s.fail(`Failed to parse config: ${(err as Error).message}`);
      raiseCliError({
        code: 'typegen_config_parse_failed',
        message: `Failed to parse config: ${(err as Error).message}`,
        hint: 'Make sure edgebase.config.ts exports a valid config object.',
      });
    }

    // Count tables from the canonical databases block
    let tableCount = 0;
    if (config.databases) {
      for (const db of Object.values(config.databases)) {
        tableCount += Object.keys(db.tables ?? {}).length;
      }
    }

    if (tableCount === 0) {
      s.warn('No tables found in config.');
    } else {
      s.succeed(`Parsed ${tableCount} table(s) from config`);
    }

    const output = generateTypes(config);
    const outputPath = path.resolve(cwd, options.output);
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, output, 'utf-8');

    if (isJson()) {
      console.log(JSON.stringify({
        status: 'success',
        tables: tableCount,
        output: options.output,
      }));
    } else if (!isQuiet()) {
      console.log(chalk.green('✅'), `Generated ${tableCount} type(s) → ${options.output}`);
    }
  });
