cmake_minimum_required(VERSION 3.16)

function(require_contains file needle)
  file(READ "${file}" contents)
  string(FIND "${contents}" "${needle}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "${file} is missing required hosted CAPTCHA contract: ${needle}")
  endif()
endfunction()

function(require_absent file needle)
  file(READ "${file}" contents)
  string(FIND "${contents}" "${needle}" position)
  if(NOT position EQUAL -1)
    message(FATAL_ERROR "${file} contains forbidden legacy CAPTCHA contract: ${needle}")
  endif()
endfunction()

function(require_compact_contains file needle)
  file(READ "${file}" contents)
  string(REGEX REPLACE "[ \t\r\n]" "" compact_contents "${contents}")
  string(FIND "${compact_contents}" "${needle}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "${file} is missing required compact packaging contract: ${needle}")
  endif()
endfunction()

set(package_provider "${UNREAL_PACKAGE_ROOT}/src/turnstile_provider.cpp")
set(package_header "${UNREAL_PACKAGE_ROOT}/include/edgebase/turnstile_provider.h")
set(package_adapter "${UNREAL_PACKAGE_ROOT}/include/edgebase/turnstile_adapter_ue.h")
set(orphan_package_auth "${UNREAL_PACKAGE_ROOT}/src/auth_client.cpp")
set(source_provider "${CPP_SDK_ROOT}/Source/EdgeBase/Private/TurnstileProvider.cpp")
set(source_header "${CPP_SDK_ROOT}/Source/EdgeBase/Public/TurnstileProvider.h")
set(source_adapter "${CPP_SDK_ROOT}/Source/EdgeBase/Public/TurnstileAdapterUE.h")
set(source_module "${CPP_SDK_ROOT}/Source/EdgeBase/Private/EdgeBaseModule.cpp")
set(source_build "${CPP_SDK_ROOT}/Source/EdgeBase/EdgeBase.Build.cs")
set(plugin_manifest "${CPP_SDK_ROOT}/EdgeBase.uplugin")
set(core_header "${CPP_SDK_ROOT}/packages/core/include/edgebase/edgebase.h")
set(core_auth "${CPP_SDK_ROOT}/packages/core/src/database_live_client.cpp")
set(core_cmake "${CPP_SDK_ROOT}/packages/core/CMakeLists.txt")
set(sync_script "${CPP_SDK_ROOT}/scripts/sync-thirdparty.sh")
set(sync_script_windows "${CPP_SDK_ROOT}/scripts/sync-thirdparty.ps1")
set(package_cmake "${UNREAL_PACKAGE_ROOT}/CMakeLists.txt")
set(thirdparty_consumer "${UNREAL_PACKAGE_ROOT}/tests/thirdparty_consumer/CMakeLists.txt")
set(thirdparty_consumer_main "${UNREAL_PACKAGE_ROOT}/tests/thirdparty_consumer/main.cpp")

if(EXISTS "${orphan_package_auth}")
  message(FATAL_ERROR
    "${orphan_package_auth} duplicates the core AuthClient and is not a CMake build input; remove it instead of shipping a drifting implementation")
endif()

foreach(file IN ITEMS
    "${package_provider}" "${package_header}" "${package_adapter}"
    "${source_provider}" "${source_header}" "${source_adapter}")
  foreach(forbidden IN ITEMS
      "getTurnstileHtml" "challenges.cloudflare.com" "edgebase://token/" "LoadString(")
    require_absent("${file}" "${forbidden}")
  endforeach()
endforeach()

foreach(file IN ITEMS "${package_provider}" "${source_provider}")
  require_contains("${file}" "/api/captcha/challenge")
  require_contains("${file}" "edgebase://message/")
  require_contains("${file}" "kMaxRawMessageBytes = 4096")
  require_contains("${file}" "kMaxTokenBytes = 2048")
  require_contains("${file}" "kMaxErrorBytes = 256")
  require_contains("${file}" "kMaxReadyBytes = 32")
  require_contains("${file}" "siteKeyCache_[baseUrl]")
  require_contains("${file}" "kSiteKeyCacheTtl = std::chrono::minutes(5)")
  require_contains("${file}" "now < cached->second.expiresAt")
  require_contains("${file}" "setClockForTesting")
  require_contains("${file}" "captcha-unavailable: config_fetch_failed")
  require_contains("${file}" "captcha-unavailable: config_invalid_response")
  require_contains("${file}" "json[\"captcha\"].is_null()")
  require_contains("${file}" "factory = webViewFactory_")
  require_contains("${file}" "tryParseChallengeMessage")
  require_contains("${file}" "hasSafeJsonDepth")
endforeach()

foreach(file IN ITEMS "${package_adapter}" "${source_adapter}")
  require_contains("${file}" ".InitialURL(ChallengeUrl)")
  require_contains("${file}" ".OnLoadError_Lambda")
  require_absent("${file}" "LoadURL(ChallengeUrl)")
  require_contains("${file}" "Url == ChallengeUrl")
  require_contains("${file}" "tryParseChallengeUri")
  require_contains("${file}" "CompleteOnce")
  require_contains("${file}" "Wait(30000)")
  require_contains("${file}" "synchronous protected auth cannot run on the Unreal Game Thread")
  require_contains("${file}" "const FWebNavigationRequest &Request")
  require_contains("${file}" "(void)Request")
  require_absent("${file}" "(const FString &Url) {")
  require_contains("${file}" "setPreflightGuard")
endforeach()

foreach(file IN ITEMS "${package_header}" "${source_header}")
  require_contains("${file}" "hostedChallengeUrl")
  require_contains("${file}" "generateSecureChannel")
  require_contains("${file}" "tryParseChallengeUri")
  require_contains("${file}" "using PreflightGuard")
  require_contains("${file}" "using Clock")
  require_contains("${file}" "SiteKeyCacheEntry")
endforeach()

foreach(file IN ITEMS "${package_provider}" "${source_provider}")
  require_contains("${file}" "if (guard)")
  require_contains("${file}" "fetchSiteKey(http)")
endforeach()
require_contains("${package_provider}" "if (guard) {\n    guard();\n  }\n  if (!http || fetchSiteKey(http).empty())")
require_contains("${source_provider}" "if (guard) guard();\n  if (!http || fetchSiteKey(http).empty())")

require_contains("${source_module}" "RegisterUnrealTurnstile")
require_contains("${source_module}" "setPreflightGuard({})")
require_contains("${source_build}" "WebBrowserWidget")
require_contains("${source_build}" "bcrypt.lib")
require_contains("${source_build}" "bEnableExceptions = true")
require_contains("${source_build}" "File.Exists(CoreLibraryPath)")
require_contains("${source_build}" "File.Exists(IxWebSocketLibraryPath)")
require_contains("${source_build}" "PublicAdditionalLibraries.Add(IxWebSocketLibraryPath)")
require_contains("${source_build}" "ixwebsocket.lib")
require_contains("${source_build}" "libixwebsocket.a")
require_contains("${source_build}" "ws2_32.lib")
require_contains("${source_build}" "PublicFrameworks.AddRange")
require_contains("${source_build}" "currently ships native ThirdParty artifacts only")
require_contains("${source_build}" "sync-thirdparty.ps1")
require_contains("${plugin_manifest}" "\"PlatformAllowList\"")
require_contains("${plugin_manifest}" "\"Win64\"")
require_contains("${plugin_manifest}" "\"Mac\"")
require_contains("${plugin_manifest}" "\"Linux\"")
require_absent("${plugin_manifest}" "\"Android\"")
require_absent("${plugin_manifest}" "\"IOS\"")
require_compact_contains("${plugin_manifest}" "\"PlatformAllowList\":[\"Win64\",\"Mac\",\"Linux\"]")
require_contains("${core_header}" "CaptchaTokenProvider")
require_contains("${core_header}" "class AuthTokenStorage")
require_contains("${core_header}" "atomically and durably replace")
require_contains("${core_header}" "getBaseUrl() const")
require_contains("${core_auth}" "setCaptchaTokenProvider")
require_contains("${core_auth}" "http_, \"oauth\", captchaToken")
require_contains("${core_auth}" "http_, \"phone\", \"\"")
require_contains("${core_auth}" "token-persistence-required")
require_contains("${core_auth}" "five-minute server checkpoint")
require_contains("${core_cmake}" "set(USE_OPEN_SSL ON")
require_contains("${sync_script}" "Always reconfigure and rebuild")
require_contains("${sync_script}" "cmake --build")
require_contains("${sync_script}" "libixwebsocket.a")
require_contains("${sync_script}" "thirdparty_consumer")
require_contains("${sync_script_windows}" "cmake --build")
require_contains("${sync_script_windows}" "edgebase_core.lib")
require_contains("${sync_script_windows}" "ixwebsocket.lib")
require_contains("${sync_script_windows}" "thirdparty_consumer")
require_contains("${thirdparty_consumer}" "add_library(edgebase_core_packaged STATIC IMPORTED")
require_contains("${thirdparty_consumer}" "add_library(ixwebsocket_packaged STATIC IMPORTED")
require_contains("${thirdparty_consumer}" "edgebase_core_packaged\n  ixwebsocket_packaged")
require_contains("${thirdparty_consumer_main}" "sdk.room")
require_contains("${package_cmake}" "turnstile_source_core_contract")
require_contains("${package_cmake}" "turnstile_source_nocore_contract")

message(STATUS "Unreal hosted CAPTCHA packaging guard passed")
