import {
  copyFileSync,
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  realpathSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  unlinkSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { basename, dirname, join, posix, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeFrontendMountPath, type FrontendConfigLike } from './frontend-config.js';
import {
  buildManagedD1DatabaseName,
  buildManagedR2BucketName,
  buildManagedWorkerName,
} from './managed-resource-names.js';
import { deriveProjectSlug, INTERNAL_D1_BINDINGS } from './project-runtime.js';
import { resolveWranglerTool } from './wrangler.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = resolve(__dirname, '../../../..');
const MONOREPO_SERVER_RUNTIME_SOURCE = resolve(__dirname, '../../../server/src');
const MONOREPO_ADMIN_BUILD_SOURCES = [
  resolve(__dirname, '../../../admin/build'),
  resolve(__dirname, '../../../server/admin-build'),
];
const CLI_NODE_MODULES_SOURCE = resolve(__dirname, '../../node_modules');
const WORKSPACE_NODE_MODULES_SOURCE = resolve(WORKSPACE_ROOT, 'node_modules');
const SERVER_NODE_MODULES_SOURCE = resolve(__dirname, '../../../server/node_modules');
const MONOREPO_SERVER_PACKAGE_MANIFEST_SOURCE = resolve(__dirname, '../../../server/package.json');
const MONOREPO_SHARED_SOURCE = resolve(__dirname, '../../../shared');
const EDGEBASE_ASSETS_DIRNAME = 'app-assets';
export { deriveProjectSlug, INTERNAL_D1_BINDINGS } from './project-runtime.js';

export type RuntimeDependencyProfile = 'portable' | 'docker';

interface RuntimePackageSelection {
  packageName: string;
  packageDir: string;
  manifestPath: string;
}

interface RuntimeScaffoldOptions {
  frontend?: FrontendConfigLike | null;
  frontendProjectDir?: string;
  configImportPath?: string;
  testConfigImportPath?: string;
  dependencyMode?: 'symlink' | 'copy';
  dependencyProfile?: RuntimeDependencyProfile;
}

export function getRuntimeRoot(projectDir: string): string {
  return join(projectDir, '.edgebase', 'runtime', 'server');
}

export function getRuntimeServerSrcDir(projectDir: string): string {
  return join(getRuntimeRoot(projectDir), 'src');
}

export function getRuntimeAdminBuildDir(projectDir: string): string {
  return join(getRuntimeRoot(projectDir), 'admin-build');
}

export function getRuntimeAssetsDir(projectDir: string): string {
  return join(getRuntimeRoot(projectDir), EDGEBASE_ASSETS_DIRNAME);
}

export function ensureRuntimeScaffold(projectDir: string, options: RuntimeScaffoldOptions = {}): void {
  const runtimeRoot = getRuntimeRoot(projectDir);
  mkdirSync(runtimeRoot, { recursive: true });

  copyRuntimeDir(resolveServerRuntimeSource(projectDir), getRuntimeServerSrcDir(projectDir));
  const adminBuildDir = getRuntimeAdminBuildDir(projectDir);
  copyRuntimeDir(resolveAdminBuildSource(projectDir), adminBuildDir);
  normalizeAdminBuildBase(adminBuildDir);
  prepareRuntimeAssets(
    projectDir,
    options.frontendProjectDir ?? projectDir,
    adminBuildDir,
    options.frontend ?? undefined,
  );
  ensureRuntimeNodeModules(
    projectDir,
    runtimeRoot,
    options.dependencyMode ?? 'symlink',
    options.dependencyProfile ?? 'portable',
  );
  ensureProjectSharedPackageLink(projectDir, options.dependencyMode ?? 'symlink');
  writeRuntimeConfigShim(projectDir, undefined, { importPath: options.configImportPath });
  writeRuntimeTestConfigShim(projectDir, { importPath: options.testConfigImportPath });
}

export function ensureLocalWranglerToml(projectDir: string): string {
  const wranglerPath = join(projectDir, 'wrangler.toml');
  if (existsSync(wranglerPath)) return wranglerPath;

  writeFileSync(
    wranglerPath,
    buildDefaultWranglerToml(undefined, deriveProjectSlug(projectDir)),
    'utf-8',
  );
  return wranglerPath;
}

export function buildDefaultWranglerToml(accountId?: string, projectName = 'edgebase'): string {
  const workerName = buildManagedWorkerName(projectName);
  const accountLine = accountId ? `account_id = "${accountId}"\n` : '';
  const internalD1Blocks = INTERNAL_D1_BINDINGS.map(
    ({ name, binding }) => `[[d1_databases]]
binding = "${binding}"
database_name = "${buildManagedD1DatabaseName(workerName, name)}"
database_id = "local"
`,
  ).join('\n');

  return `# Auto-generated by edgebase
name = "${workerName}"
${accountLine}main = ".edgebase/runtime/server/src/index.ts"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "DATABASE", class_name = "DatabaseDO" },
  { name = "AUTH", class_name = "AuthDO" },
  { name = "DATABASE_LIVE", class_name = "DatabaseLiveDO" },
  { name = "ROOMS", class_name = "RoomsDO" },
  { name = "LOGS", class_name = "LogsDO" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DatabaseDO", "AuthDO", "DatabaseLiveDO", "RoomsDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LogsDO"]

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "${buildManagedR2BucketName(workerName)}"

[[kv_namespaces]]
binding = "KV"
id = "local"

${internalD1Blocks}

[assets]
directory = ".edgebase/runtime/server/app-assets"
binding = "ASSETS"
run_worker_first = true
`;
}

export function resolveWranglerCommand(): { command: string; argsPrefix: string[] } {
  return resolveWranglerTool(process.cwd());
}

function copyRuntimeDir(source: string, target: string): void {
  if (!existsSync(source)) {
    throw new Error(`Runtime scaffold source is missing: ${source}`);
  }
  mkdirSync(target, { recursive: true });
  cpSync(source, target, {
    recursive: true,
    force: true,
    filter: (sourcePath) => basename(sourcePath) !== '_functions-registry.ts',
  });
}

function resolveServerRuntimeSource(projectDir: string): string {
  const candidates = dedupeCandidates([
    MONOREPO_SERVER_RUNTIME_SOURCE,
    join(projectDir, 'node_modules', '@edge-base', 'server', 'src'),
    resolve(CLI_NODE_MODULES_SOURCE, '@edge-base/server', 'src'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edge-base/server', 'src'),
  ]);

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'index.ts'))) {
      return candidate;
    }
  }

  throw new Error(`Runtime scaffold source is missing. Checked: ${candidates.join(', ')}`);
}

function resolveAdminBuildSource(projectDir: string): string {
  const candidates = dedupeCandidates([
    ...MONOREPO_ADMIN_BUILD_SOURCES,
    join(projectDir, 'node_modules', '@edge-base', 'server', 'admin-build'),
    resolve(CLI_NODE_MODULES_SOURCE, '@edge-base/server', 'admin-build'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edge-base/server', 'admin-build'),
  ]);

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'index.html'))) {
      return candidate;
    }
  }

  throw new Error(`Admin build source is missing. Checked: ${candidates.join(', ')}`);
}

function prepareRuntimeAssets(
  projectDir: string,
  sourceProjectDir: string,
  adminBuildDir: string,
  frontend: FrontendConfigLike | undefined,
): void {
  const assetsDir = getRuntimeAssetsDir(projectDir);
  rmSync(assetsDir, { recursive: true, force: true });
  mkdirSync(assetsDir, { recursive: true });

  copyRuntimeDir(adminBuildDir, join(assetsDir, 'admin'));
  copyFrontendBuild(sourceProjectDir, assetsDir, frontend);
}

function copyFrontendBuild(
  projectDir: string,
  assetsDir: string,
  frontend: FrontendConfigLike | undefined,
): void {
  if (!frontend?.directory) return;

  const source = resolve(projectDir, frontend.directory);
  if (!existsSync(source)) {
    throw new Error(`Frontend build directory is missing: ${source}`);
  }

  const mountPath = normalizeFrontendMountPath(frontend.mountPath);
  if (mountPath === '/') {
    const conflicts = readdirSync(source).filter((entry) => entry === 'admin');
    if (conflicts.length > 0) {
      throw new Error(
        `Frontend build directory '${frontend.directory}' contains reserved top-level entries: ${conflicts.join(', ')}.`,
      );
    }
  }

  const target = mountPath === '/' ? assetsDir : join(assetsDir, mountPath.slice(1));
  mkdirSync(target, { recursive: true });
  copyRuntimeDir(source, target);
}

function normalizeAdminBuildBase(adminBuildDir: string): void {
  const indexPath = join(adminBuildDir, 'index.html');
  if (!existsSync(indexPath)) return;

  const content = readFileSync(indexPath, 'utf-8');
  const normalized = content
    .replace(/href="\/favicon\.svg"/g, 'href="/admin/favicon.svg"')
    .replace(/href="\/_app\//g, 'href="/admin/_app/')
    .replace(/import\("\/_app\//g, 'import("/admin/_app/')
    .replace(/base:\s*""/g, 'base: "/admin"');

  if (normalized !== content) {
    writeFileSync(indexPath, normalized, 'utf-8');
  }
}

function ensureRuntimeNodeModules(
  projectDir: string,
  runtimeRoot: string,
  mode: 'symlink' | 'copy',
  profile: RuntimeDependencyProfile,
): void {
  const source = resolveRuntimeNodeModulesSource(projectDir, mode);
  if (!source) return;

  const target = join(runtimeRoot, 'node_modules');
  if (mode === 'copy') {
    materializeNodeModulesTree(
      source,
      target,
      getRuntimeNodeModulesCandidates(projectDir, mode),
      resolveRuntimeDependencySelection(projectDir, profile),
    );
    return;
  }
  const currentLink = readExistingSymlinkTarget(target);
  if (currentLink === source) return;
  if (currentLink !== null || existsSync(target)) {
    rmSync(target, { recursive: true, force: true });
  }

  symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
}

export function ensureProjectSharedPackageLink(
  projectDir: string,
  mode: 'symlink' | 'copy' = 'symlink',
): void {
  const source = resolveSharedPackageSource(projectDir);
  if (!source) return;

  for (const root of resolveSharedPackageLinkRoots(projectDir)) {
    ensureSharedPackageLinkAtRoot(root, source, mode);
  }
}

function resolveRuntimeNodeModulesSource(projectDir: string, mode: 'symlink' | 'copy' = 'symlink'): string | null {
  return resolveRuntimeNodeModulesSourceFromCandidates(getRuntimeNodeModulesCandidates(projectDir, mode));
}

export function resolveRuntimeNodeModulesSourceFromCandidates(candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
}

function resolveSharedPackageSource(projectDir: string): string | null {
  return resolveSharedPackageSourceFromCandidates(getSharedPackageSourceCandidates(projectDir));
}

export function resolveSharedPackageSourceFromCandidates(candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'src', 'index.ts'))) {
      return candidate;
    }
  }

  return null;
}

function getRuntimeNodeModulesCandidates(projectDir: string, mode: 'symlink' | 'copy' = 'symlink'): string[] {
  if (mode === 'copy') {
    return dedupeCandidates([
      SERVER_NODE_MODULES_SOURCE,
      CLI_NODE_MODULES_SOURCE,
      join(projectDir, 'node_modules'),
      WORKSPACE_NODE_MODULES_SOURCE,
    ]);
  }

  return dedupeCandidates([
    SERVER_NODE_MODULES_SOURCE,
    CLI_NODE_MODULES_SOURCE,
    WORKSPACE_NODE_MODULES_SOURCE,
    join(projectDir, 'node_modules'),
  ]);
}

function materializeNodeModulesTree(
  sourceRoot: string,
  targetRoot: string,
  candidateRoots: string[],
  selectedPackages?: RuntimePackageSelection[] | null,
): void {
  rmSync(targetRoot, { recursive: true, force: true });
  mkdirSync(targetRoot, { recursive: true });

  const normalizedRoots = dedupeCandidates(candidateRoots)
    .filter((candidate) => existsSync(candidate))
    .map((candidate) => resolve(candidate))
    .sort((left, right) => right.length - left.length);
  const copiedTargets = new Set<string>();

  if (selectedPackages && selectedPackages.length > 0) {
    for (const selection of selectedPackages) {
      materializeNodeModulesEntry(
        selection.packageDir,
        join(targetRoot, ...selection.packageName.split('/')),
        targetRoot,
        normalizedRoots,
        copiedTargets,
      );
    }
    return;
  }

  for (const entry of readdirSync(sourceRoot)) {
    materializeNodeModulesEntry(
      join(sourceRoot, entry),
      join(targetRoot, entry),
      targetRoot,
      normalizedRoots,
      copiedTargets,
    );
  }
}

function resolvePackageDirectoryPath(packageName: string, candidateRoots: string[]): string | null {
  const topLevelEntry = resolveTopLevelPackageEntry(packageName, candidateRoots);
  if (topLevelEntry) {
    return topLevelEntry;
  }

  const packageSegments = packageName.split('/');
  for (const candidateRoot of dedupeCandidates(candidateRoots)) {
    const pnpmDir = join(candidateRoot, '.pnpm');
    if (!existsSync(pnpmDir)) continue;

    for (const entry of readdirSync(pnpmDir)) {
      const candidatePath = join(pnpmDir, entry, 'node_modules', ...packageSegments);
      if (existsSync(candidatePath)) {
        return candidatePath;
      }
    }
  }

  return null;
}

function resolveTopLevelPackageEntry(packageName: string, candidateRoots: string[]): string | null {
  const packagePath = packageName.split('/');
  for (const candidateRoot of candidateRoots) {
    const candidatePath = join(candidateRoot, ...packagePath);
    if (existsSync(candidatePath)) {
      return candidatePath;
    }
  }

  return null;
}

function materializeNodeModulesEntry(
  sourceEntry: string,
  targetEntry: string,
  targetRoot: string,
  candidateRoots: string[],
  copiedTargets: Set<string>,
  skipNestedNodeModules = false,
): void {
  const stat = lstatSync(sourceEntry);

  if (stat.isSymbolicLink()) {
    const sourceLinkTarget = readlinkSync(sourceEntry);
    const resolvedSourceTarget = resolve(dirname(sourceEntry), sourceLinkTarget);
    const sourceContainerRoot = findContainingRoot(resolvedSourceTarget, candidateRoots);
    if (!existsSync(resolvedSourceTarget)) {
      rmSync(targetEntry, { recursive: true, force: true });
      mkdirSync(dirname(targetEntry), { recursive: true });
      symlinkSync(
        buildDirectoryLinkTarget(targetEntry, resolvedSourceTarget),
        targetEntry,
        process.platform === 'win32' ? 'junction' : 'dir',
      );
      return;
    }

    if (!sourceContainerRoot) {
      const targetKey = `${resolvedSourceTarget}=>${targetEntry}`;
      if (copiedTargets.has(targetKey)) {
        return;
      }
      copiedTargets.add(targetKey);
      materializeNodeModulesEntry(
        resolvedSourceTarget,
        targetEntry,
        targetRoot,
        candidateRoots,
        copiedTargets,
        true,
      );
      return;
    }

    const materialization = getNodeModulesMaterialization(resolvedSourceTarget, sourceContainerRoot, targetRoot);
    const targetKey = `${materialization.sourceRoot}=>${materialization.targetRoot}`;
    if (!copiedTargets.has(targetKey)) {
      copiedTargets.add(targetKey);
      materializeNodeModulesEntry(
        materialization.sourceRoot,
        materialization.targetRoot,
        targetRoot,
        candidateRoots,
        copiedTargets,
        skipNestedNodeModules,
      );
    }

    rmSync(targetEntry, { recursive: true, force: true });
    mkdirSync(dirname(targetEntry), { recursive: true });
    symlinkSync(
      buildDirectoryLinkTarget(targetEntry, materialization.targetPath),
      targetEntry,
      process.platform === 'win32' ? 'junction' : 'dir',
    );
    return;
  }

  if (stat.isDirectory()) {
    mkdirSync(targetEntry, { recursive: true });
    for (const entry of readdirSync(sourceEntry)) {
      if (skipNestedNodeModules && entry === 'node_modules') {
        continue;
      }
      materializeNodeModulesEntry(
        join(sourceEntry, entry),
        join(targetEntry, entry),
        targetRoot,
        candidateRoots,
        copiedTargets,
        skipNestedNodeModules,
      );
    }
    return;
  }

  mkdirSync(dirname(targetEntry), { recursive: true });
  copyFileSync(sourceEntry, targetEntry);
}

function findContainingRoot(targetPath: string, candidateRoots: string[]): string | null {
  for (const candidateRoot of candidateRoots) {
    if (getRelativePathSegmentsWithinRoot(candidateRoot, targetPath) !== null) {
      return candidateRoot;
    }
  }

  return null;
}

function getNodeModulesMaterialization(
  sourcePath: string,
  sourceContainerRoot: string,
  targetRoot: string,
): { sourceRoot: string; targetRoot: string; targetPath: string } {
  const relativeSegments = getRelativePathSegmentsWithinRoot(sourceContainerRoot, sourcePath);
  if (!relativeSegments) {
    throw new Error(`Could not resolve '${sourcePath}' inside runtime dependency root '${sourceContainerRoot}'.`);
  }

  const targetPath = join(targetRoot, ...relativeSegments);

  if (relativeSegments[0] === '.pnpm' && relativeSegments.length >= 2) {
    const packageRoot = join(sourceContainerRoot, '.pnpm', relativeSegments[1]);
    return {
      sourceRoot: packageRoot,
      targetRoot: join(targetRoot, '.pnpm', relativeSegments[1]),
      targetPath,
    };
  }

  return {
    sourceRoot: sourcePath,
    targetRoot: targetPath,
    targetPath,
  };
}

function getRelativePathSegmentsWithinRoot(rootPath: string, targetPath: string): string[] | null {
  const rootSegments = splitCrossPlatformPathSegments(rootPath);
  const targetSegments = splitCrossPlatformPathSegments(targetPath);

  if (rootSegments.length > targetSegments.length) {
    return null;
  }

  for (let index = 0; index < rootSegments.length; index += 1) {
    if (rootSegments[index] !== targetSegments[index]) {
      return null;
    }
  }

  return targetSegments.slice(rootSegments.length);
}

function splitCrossPlatformPathSegments(pathValue: string): string[] {
  const normalized = normalizeCrossPlatformPath(pathValue);
  return normalized.split('/').filter(Boolean);
}

function normalizeCrossPlatformPath(pathValue: string): string {
  let normalized = pathValue.replace(/\\/g, '/').replace(/\/+/g, '/');
  if (normalized.length > 1 && normalized.endsWith('/')) {
    normalized = normalized.slice(0, -1);
  }
  if (/^[A-Z]:($|\/)/.test(normalized)) {
    normalized = `${normalized[0].toLowerCase()}${normalized.slice(1)}`;
  }
  return normalized;
}

function buildDirectoryLinkTarget(linkPath: string, destinationPath: string, platform = process.platform): string {
  if (platform === 'win32') {
    if (/^[A-Za-z]:[\\/]/.test(destinationPath)) {
      return destinationPath.replace(/\//g, '\\');
    }
    return resolve(destinationPath);
  }

  const sourceDir = normalizeCrossPlatformPath(dirname(linkPath));
  const targetPath = normalizeCrossPlatformPath(destinationPath);
  return posix.relative(sourceDir, targetPath) || '.';
}

export const __runtimeScaffoldTestUtils = {
  buildDirectoryLinkTarget,
  findContainingRoot,
  getNodeModulesMaterialization,
  getRelativePathSegmentsWithinRoot,
  resolvePackageSelectionFromManifestCandidates,
  resolvePackageDirectoryPath,
  resolveRuntimePackageSelections,
  resolveRuntimePackageSelectionsFromInitialSelections,
};

function getSharedPackageSourceCandidates(projectDir: string): string[] {
  return dedupeCandidates([
    join(projectDir, 'node_modules', '@edge-base', 'shared'),
    resolve(CLI_NODE_MODULES_SOURCE, '@edge-base/shared'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edge-base/shared'),
    resolve(SERVER_NODE_MODULES_SOURCE, '@edge-base/shared'),
    MONOREPO_SHARED_SOURCE,
  ]);
}

function resolveRuntimeDependencySelection(
  projectDir: string,
  profile: RuntimeDependencyProfile,
): RuntimePackageSelection[] | null {
  const candidateRoots = getRuntimeNodeModulesCandidates(projectDir, 'copy');
  const serverDependencies = readPackageDependencyNamesFromCandidates(
    getServerPackageManifestCandidates(projectDir),
  );
  if (!serverDependencies) {
    return null;
  }

  const initialSelections: RuntimePackageSelection[] = [];
  for (const packageName of dedupeCandidates(serverDependencies)) {
    const selection = resolveRuntimePackageSelection(packageName, candidateRoots);
    if (selection) {
      initialSelections.push(selection);
    }
  }

  if (profile === 'portable') {
    const wranglerSelection =
      resolvePackageSelectionFromManifestCandidates(
        'wrangler',
        getPortableWranglerManifestCandidates(projectDir),
      ) ?? resolveRuntimePackageSelection('wrangler', candidateRoots);
    if (wranglerSelection) {
      initialSelections.push(wranglerSelection);
    }
  }

  return resolveRuntimePackageSelectionsFromInitialSelections(initialSelections, candidateRoots);
}

function getPortableWranglerManifestCandidates(projectDir: string): string[] {
  return dedupeCandidates([
    join(projectDir, 'node_modules', 'wrangler', 'package.json'),
    resolve(CLI_NODE_MODULES_SOURCE, 'wrangler', 'package.json'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, 'wrangler', 'package.json'),
    resolve(SERVER_NODE_MODULES_SOURCE, 'wrangler', 'package.json'),
  ]);
}

function getServerPackageManifestCandidates(projectDir: string): string[] {
  return dedupeCandidates([
    MONOREPO_SERVER_PACKAGE_MANIFEST_SOURCE,
    join(projectDir, 'node_modules', '@edge-base', 'server', 'package.json'),
    resolve(CLI_NODE_MODULES_SOURCE, '@edge-base', 'server', 'package.json'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edge-base', 'server', 'package.json'),
  ]);
}

function readPackageDependencyNamesFromCandidates(candidates: string[]): string[] | null {
  for (const candidate of dedupeCandidates(candidates)) {
    if (!existsSync(candidate)) continue;

    try {
      return readPackageDependencyNames(candidate);
    } catch {
      continue;
    }
  }

  return null;
}

function resolveRuntimePackageSelections(
  initialPackages: string[],
  candidateRoots: string[],
): RuntimePackageSelection[] {
  const initialSelections: RuntimePackageSelection[] = [];

  for (const packageName of dedupeCandidates(initialPackages)) {
    const selection = resolveRuntimePackageSelection(packageName, candidateRoots);
    if (!selection) {
      continue;
    }

    initialSelections.push(selection);
  }

  return resolveRuntimePackageSelectionsFromInitialSelections(initialSelections, candidateRoots);
}

function resolveRuntimePackageSelectionsFromInitialSelections(
  initialSelections: RuntimePackageSelection[],
  candidateRoots: string[],
): RuntimePackageSelection[] {
  const selections = new Map<string, RuntimePackageSelection>();
  const visitedManifestPaths = new Set<string>();
  const queue: RuntimePackageSelection[] = [];

  for (const selection of initialSelections) {
    if (selections.has(selection.packageName)) {
      continue;
    }
    selections.set(selection.packageName, selection);
    queue.push(selection);
  }

  while (queue.length > 0) {
    const selection = queue.shift();
    if (!selection || visitedManifestPaths.has(selection.manifestPath)) {
      continue;
    }

    visitedManifestPaths.add(selection.manifestPath);
    const packageRequire = createRequire(selection.manifestPath);

    for (const dependencyName of readPackageDependencyNames(selection.manifestPath)) {
      const dependencySelection = resolveRuntimePackageSelection(
        dependencyName,
        candidateRoots,
        packageRequire,
      );
      if (!dependencySelection) {
        continue;
      }

      queue.push(dependencySelection);
      if (!selections.has(dependencyName)) {
        selections.set(dependencyName, dependencySelection);
      }
    }
  }

  return Array.from(selections.values());
}

function resolvePackageSelectionFromManifestCandidates(
  packageName: string,
  manifestCandidates: string[],
): RuntimePackageSelection | null {
  for (const manifestCandidate of dedupeCandidates(manifestCandidates)) {
    if (!existsSync(manifestCandidate)) {
      continue;
    }

    try {
      const rawManifestPath = resolve(manifestCandidate);
      const resolvedManifestPath = realpathSync(manifestCandidate);
      const packageJson = JSON.parse(readFileSync(resolvedManifestPath, 'utf-8')) as { name?: string };
      if (packageJson.name !== packageName) {
        continue;
      }

      return {
        packageName,
        packageDir: dirname(rawManifestPath),
        manifestPath: resolvedManifestPath,
      };
    } catch {
      continue;
    }
  }

  return null;
}

function resolveRuntimePackageSelection(
  packageName: string,
  candidateRoots: string[],
  packageRequire?: NodeJS.Require,
): RuntimePackageSelection | null {
  const location = resolvePackageManifestLocation(packageName, candidateRoots, packageRequire);
  if (!location) {
    return null;
  }

  return {
    packageName,
    packageDir: location.packageDir,
    manifestPath: location.manifestPath,
  };
}

function resolvePackageManifestLocation(
  packageName: string,
  candidateRoots: string[],
  packageRequire?: NodeJS.Require,
): { packageDir: string; manifestPath: string } | null {
  if (packageRequire) {
    try {
      const rawManifestPath = packageRequire.resolve(`${packageName}/package.json`);
      if (existsSync(rawManifestPath)) {
        return {
          packageDir: dirname(resolve(rawManifestPath)),
          manifestPath: realpathSync(rawManifestPath),
        };
      }
    } catch {
      // Fall back to the candidate-root scan below so workspace shims and
      // fixture tests can still resolve packages outside the package graph.
    }
  }

  const packageDir = resolvePackageDirectoryPath(packageName, candidateRoots);
  if (!packageDir) {
    return null;
  }

  const rawManifestPath = join(packageDir, 'package.json');
  if (!existsSync(rawManifestPath)) {
    return null;
  }

  return {
    packageDir,
    manifestPath: realpathSync(rawManifestPath),
  };
}

function readPackageDependencyNames(packageJsonPath: string): string[] {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8')) as {
    dependencies?: Record<string, string>;
    optionalDependencies?: Record<string, string>;
  };
  return [
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.optionalDependencies ?? {}),
  ];
}

function dedupeCandidates(candidates: string[]): string[] {
  return Array.from(new Set(candidates));
}

export function resolveSharedPackageLinkRoots(projectDir: string): string[] {
  const roots = new Set([projectDir]);
  const workspaceRoot = findWorkspaceRoot(projectDir);
  if (workspaceRoot) {
    roots.add(workspaceRoot);
  }
  return Array.from(roots);
}

function ensureSharedPackageLinkAtRoot(
  rootDir: string,
  source: string,
  mode: 'symlink' | 'copy',
): void {
  const target = join(rootDir, 'node_modules', '@edge-base', 'shared');
  const markerPath = join(target, '.edgebase-shim');
  const normalizedSource = resolve(source);
  const normalizedTarget = resolve(target);

  if (existsSync(target)) {
    if (normalizedSource === normalizedTarget) {
      return;
    }
    try {
      const stat = lstatSync(target);
      if (stat.isSymbolicLink()) {
        unlinkSync(target);
      } else if (!existsSync(markerPath)) {
        return;
      }
    } catch {
      return;
    }
  }

  mkdirSync(target, { recursive: true });
  writeFileSync(join(target, 'package.json'), buildSharedShimPackageJson(), 'utf-8');
  writeFileSync(markerPath, 'edgebase-shared-shim\n', 'utf-8');
  if (mode === 'copy') {
    replaceDirectoryContents(join(source, 'src'), join(target, 'src'));
  } else {
    ensureDirectorySymlink(join(source, 'src'), join(target, 'src'));
  }
}

function findWorkspaceRoot(startDir: string): string | null {
  let currentDir = resolve(startDir);

  while (true) {
    if (existsSync(join(currentDir, 'pnpm-workspace.yaml')) || existsSync(join(currentDir, '.git'))) {
      return currentDir;
    }

    const parentDir = dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

function ensureDirectorySymlink(source: string, target: string): void {
  const normalizedSource = resolve(source);
  const currentLink = readExistingSymlinkTarget(target);
  if (currentLink === normalizedSource) return;
  if (currentLink !== null) {
    unlinkSync(target);
  } else if (existsSync(target)) {
    rmSync(target, { recursive: true, force: true });
  }

  try {
    symlinkSync(normalizedSource, target, process.platform === 'win32' ? 'junction' : 'dir');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'EEXIST') {
      throw error;
    }

    const retryLink = readExistingSymlinkTarget(target);
    if (retryLink === normalizedSource) {
      return;
    }

    if (retryLink !== null) {
      unlinkSync(target);
    } else {
      rmSync(target, { recursive: true, force: true });
    }
    symlinkSync(normalizedSource, target, process.platform === 'win32' ? 'junction' : 'dir');
  }
}

function replaceDirectoryContents(
  source: string,
  target: string,
  options: { dereference?: boolean; verbatimSymlinks?: boolean } = {},
): void {
  rmSync(target, { recursive: true, force: true });
  mkdirSync(dirname(target), { recursive: true });
  if ((options.dereference ?? true) === false && (options.verbatimSymlinks ?? false) === true) {
    copyDirectoryTreePreservingSymlinks(source, target);
    return;
  }
  cpSync(source, target, {
    recursive: true,
    force: true,
    dereference: options.dereference ?? true,
    verbatimSymlinks: options.verbatimSymlinks ?? false,
  });
}

function copyDirectoryTreePreservingSymlinks(source: string, target: string): void {
  const stat = lstatSync(source);

  if (stat.isSymbolicLink()) {
    rmSync(target, { recursive: true, force: true });
    mkdirSync(dirname(target), { recursive: true });
    const linkTarget = readlinkSync(source);
    symlinkSync(linkTarget, target, process.platform === 'win32' ? 'junction' : 'dir');
    return;
  }

  if (stat.isDirectory()) {
    mkdirSync(target, { recursive: true });
    for (const entry of readdirSync(source)) {
      copyDirectoryTreePreservingSymlinks(join(source, entry), join(target, entry));
    }
    return;
  }

  mkdirSync(dirname(target), { recursive: true });
  copyFileSync(source, target);
}

function readExistingSymlinkTarget(target: string): string | null {
  try {
    if (!lstatSync(target).isSymbolicLink()) {
      return null;
    }
    return resolve(dirname(target), readlinkSync(target));
  } catch {
    return null;
  }
}

function buildSharedShimPackageJson(): string {
  return `${JSON.stringify(
    {
      name: '@edge-base/shared',
      private: true,
      type: 'module',
      main: './src/index.ts',
      types: './src/index.ts',
      exports: {
        '.': {
          types: './src/index.ts',
          import: './src/index.ts',
          default: './src/index.ts',
          require: './src/index.ts',
        },
      },
    },
    null,
    2,
  )}\n`;
}

function buildRuntimeConfigShimContents(
  injectedEnv?: Record<string, string>,
  importPath = '../../../../edgebase.config.ts',
): string {
  const normalizedEnv = Object.fromEntries(
    Object.entries(injectedEnv ?? {}).filter(([, value]) => typeof value === 'string'),
  );

  if (Object.keys(normalizedEnv).length === 0) {
    return `// Auto-generated by edgebase CLI. Re-export the runtime config module with a static path so Wrangler can bundle it.
import config from '${importPath}';

export default config;
`;
  }

  return `// Auto-generated by edgebase CLI. Inject local config env before evaluating the runtime config module.
const injectedEnv = ${JSON.stringify(normalizedEnv, null, 2)} as Record<string, string>;

if (typeof process !== 'undefined' && process?.env) {
  for (const [key, value] of Object.entries(injectedEnv)) {
    if (typeof value === 'string' && process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

const mod = await import('${importPath}');
const config = (mod as { default?: unknown }).default ?? mod;

export default config;
`;
}

export function writeRuntimeConfigShim(
  projectDir: string,
  injectedEnv?: Record<string, string>,
  options?: { importPath?: string },
): void {
  const shimPath = join(getRuntimeServerSrcDir(projectDir), 'generated-config.ts');
  writeFileSync(
    shimPath,
    buildRuntimeConfigShimContents(injectedEnv, options?.importPath),
    'utf-8',
  );
}

function writeRuntimeTestConfigShim(
  projectDir: string,
  options?: { importPath?: string },
): void {
  const shimPath = join(getRuntimeRoot(projectDir), 'edgebase.test.config.ts');
  const importPath = options?.importPath ?? (() => {
    const tsConfigPath = join(projectDir, 'edgebase.test.config.ts');
    const jsConfigPath = join(projectDir, 'edgebase.test.config.js');
    return existsSync(tsConfigPath)
      ? '../../../edgebase.test.config.ts'
      : existsSync(jsConfigPath)
        ? '../../../edgebase.test.config.js'
        : './src/generated-config.ts';
  })();

  writeFileSync(
    shimPath,
    `// Auto-generated by edgebase CLI. Keep the runtime test-config import resolvable in scaffolded dev environments.
// If the project does not define a dedicated test config, fall back to the generated runtime config shim.
import config from '${importPath}';

export default config;
`,
    'utf-8',
  );
}
