import {
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildManagedD1DatabaseName } from './managed-resource-names.js';
import { deriveProjectSlug, INTERNAL_D1_BINDINGS } from './project-runtime.js';
import { resolveWranglerTool } from './wrangler.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = resolve(__dirname, '../../../..');
const MONOREPO_SERVER_RUNTIME_SOURCE = resolve(__dirname, '../../../server/src');
const MONOREPO_ADMIN_BUILD_SOURCES = [
  resolve(__dirname, '../../../admin/build'),
  resolve(__dirname, '../../../server/admin-build'),
];
const CLI_NODE_MODULES_SOURCE = resolve(__dirname, '../../node_modules');
const WORKSPACE_NODE_MODULES_SOURCE = resolve(WORKSPACE_ROOT, 'node_modules');
const SERVER_NODE_MODULES_SOURCE = resolve(__dirname, '../../../server/node_modules');
const MONOREPO_SHARED_SOURCE = resolve(__dirname, '../../../shared');
export { deriveProjectSlug, INTERNAL_D1_BINDINGS } from './project-runtime.js';

export function getRuntimeRoot(projectDir: string): string {
  return join(projectDir, '.edgebase', 'runtime', 'server');
}

export function getRuntimeServerSrcDir(projectDir: string): string {
  return join(getRuntimeRoot(projectDir), 'src');
}

export function getRuntimeAdminBuildDir(projectDir: string): string {
  return join(getRuntimeRoot(projectDir), 'admin-build');
}

export function ensureRuntimeScaffold(projectDir: string): void {
  const runtimeRoot = getRuntimeRoot(projectDir);
  mkdirSync(runtimeRoot, { recursive: true });

  copyRuntimeDir(resolveServerRuntimeSource(projectDir), getRuntimeServerSrcDir(projectDir));
  const adminBuildDir = getRuntimeAdminBuildDir(projectDir);
  copyRuntimeDir(resolveAdminBuildSource(projectDir), adminBuildDir);
  normalizeAdminBuildBase(adminBuildDir);
  ensureRuntimeNodeModulesLink(projectDir, runtimeRoot);
  ensureProjectSharedPackageLink(projectDir);
  writeRuntimeConfigShim(projectDir);
  writeRuntimeTestConfigShim(projectDir);
}

export function ensureLocalWranglerToml(projectDir: string): string {
  const wranglerPath = join(projectDir, 'wrangler.toml');
  if (existsSync(wranglerPath)) return wranglerPath;

  writeFileSync(
    wranglerPath,
    buildDefaultWranglerToml(undefined, deriveProjectSlug(projectDir)),
    'utf-8',
  );
  return wranglerPath;
}

export function buildDefaultWranglerToml(accountId?: string, projectName = 'edgebase'): string {
  const accountLine = accountId ? `account_id = "${accountId}"\n` : '';
  const internalD1Blocks = INTERNAL_D1_BINDINGS.map(
    ({ name, binding }) => `[[d1_databases]]
binding = "${binding}"
database_name = "${buildManagedD1DatabaseName(projectName, name)}"
database_id = "local"
`,
  ).join('\n');

  return `# Auto-generated by edgebase
name = "${projectName}"
${accountLine}main = ".edgebase/runtime/server/src/index.ts"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "DATABASE", class_name = "DatabaseDO" },
  { name = "AUTH", class_name = "AuthDO" },
  { name = "DATABASE_LIVE", class_name = "DatabaseLiveDO" },
  { name = "ROOMS", class_name = "RoomsDO" },
  { name = "LOGS", class_name = "LogsDO" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DatabaseDO", "AuthDO"]
new_classes = ["DatabaseLiveDO", "RoomsDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LogsDO"]

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "${projectName}-storage"

[[kv_namespaces]]
binding = "KV"
id = "local"

${internalD1Blocks}

[assets]
directory = ".edgebase/runtime/server/admin-build"
binding = "ASSETS"
run_worker_first = true
`;
}

export function resolveWranglerCommand(): { command: string; argsPrefix: string[] } {
  return resolveWranglerTool(process.cwd());
}

function copyRuntimeDir(source: string, target: string): void {
  if (!existsSync(source)) {
    throw new Error(`Runtime scaffold source is missing: ${source}`);
  }
  mkdirSync(target, { recursive: true });
  cpSync(source, target, {
    recursive: true,
    force: true,
    filter: (sourcePath) => basename(sourcePath) !== '_functions-registry.ts',
  });
}

function resolveServerRuntimeSource(projectDir: string): string {
  const candidates = dedupeCandidates([
    join(projectDir, 'node_modules', '@edgebase', 'server', 'src'),
    resolve(CLI_NODE_MODULES_SOURCE, '@edgebase/server', 'src'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edgebase/server', 'src'),
    MONOREPO_SERVER_RUNTIME_SOURCE,
  ]);

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'index.ts'))) {
      return candidate;
    }
  }

  throw new Error(`Runtime scaffold source is missing. Checked: ${candidates.join(', ')}`);
}

function resolveAdminBuildSource(projectDir: string): string {
  const candidates = dedupeCandidates([
    join(projectDir, 'node_modules', '@edgebase', 'server', 'admin-build'),
    resolve(CLI_NODE_MODULES_SOURCE, '@edgebase/server', 'admin-build'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edgebase/server', 'admin-build'),
    ...MONOREPO_ADMIN_BUILD_SOURCES,
  ]);

  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'index.html'))) {
      return candidate;
    }
  }

  throw new Error(`Admin build source is missing. Checked: ${candidates.join(', ')}`);
}

function normalizeAdminBuildBase(adminBuildDir: string): void {
  const indexPath = join(adminBuildDir, 'index.html');
  if (!existsSync(indexPath)) return;

  const content = readFileSync(indexPath, 'utf-8');
  const normalized = content
    .replace(/href="\/favicon\.svg"/g, 'href="/admin/favicon.svg"')
    .replace(/href="\/_app\//g, 'href="/admin/_app/')
    .replace(/import\("\/_app\//g, 'import("/admin/_app/')
    .replace(/base:\s*""/g, 'base: "/admin"');

  if (normalized !== content) {
    writeFileSync(indexPath, normalized, 'utf-8');
  }
}

function ensureRuntimeNodeModulesLink(projectDir: string, runtimeRoot: string): void {
  const source = resolveRuntimeNodeModulesSource(projectDir);
  if (!source) return;

  const target = join(runtimeRoot, 'node_modules');
  const currentLink = readExistingSymlinkTarget(target);
  if (currentLink === source) return;
  if (currentLink !== null || existsSync(target)) {
    rmSync(target, { recursive: true, force: true });
  }

  symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
}

export function ensureProjectSharedPackageLink(projectDir: string): void {
  const source = resolveSharedPackageSource(projectDir);
  if (!source) return;

  for (const root of resolveSharedPackageLinkRoots(projectDir)) {
    ensureSharedPackageLinkAtRoot(root, source);
  }
}

function resolveRuntimeNodeModulesSource(projectDir: string): string | null {
  return resolveRuntimeNodeModulesSourceFromCandidates(getRuntimeNodeModulesCandidates(projectDir));
}

export function resolveRuntimeNodeModulesSourceFromCandidates(candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
}

function resolveSharedPackageSource(projectDir: string): string | null {
  return resolveSharedPackageSourceFromCandidates(getSharedPackageSourceCandidates(projectDir));
}

export function resolveSharedPackageSourceFromCandidates(candidates: string[]): string | null {
  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'src', 'index.ts'))) {
      return candidate;
    }
  }

  return null;
}

function getRuntimeNodeModulesCandidates(projectDir: string): string[] {
  return dedupeCandidates([
    SERVER_NODE_MODULES_SOURCE,
    CLI_NODE_MODULES_SOURCE,
    WORKSPACE_NODE_MODULES_SOURCE,
    join(projectDir, 'node_modules'),
  ]);
}

function getSharedPackageSourceCandidates(projectDir: string): string[] {
  return dedupeCandidates([
    resolve(CLI_NODE_MODULES_SOURCE, '@edgebase/shared'),
    resolve(WORKSPACE_NODE_MODULES_SOURCE, '@edgebase/shared'),
    resolve(SERVER_NODE_MODULES_SOURCE, '@edgebase/shared'),
    MONOREPO_SHARED_SOURCE,
    join(projectDir, 'node_modules', '@edgebase', 'shared'),
  ]);
}

function dedupeCandidates(candidates: string[]): string[] {
  return Array.from(new Set(candidates));
}

export function resolveSharedPackageLinkRoots(projectDir: string): string[] {
  const roots = new Set([projectDir]);
  const workspaceRoot = findWorkspaceRoot(projectDir);
  if (workspaceRoot) {
    roots.add(workspaceRoot);
  }
  return Array.from(roots);
}

function ensureSharedPackageLinkAtRoot(rootDir: string, source: string): void {
  const target = join(rootDir, 'node_modules', '@edgebase', 'shared');
  const markerPath = join(target, '.edgebase-shim');
  const normalizedSource = resolve(source);
  const normalizedTarget = resolve(target);

  if (existsSync(target)) {
    if (normalizedSource === normalizedTarget) {
      return;
    }
    try {
      const stat = lstatSync(target);
      if (stat.isSymbolicLink()) {
        rmSync(target, { recursive: true, force: true });
      } else if (!existsSync(markerPath)) {
        return;
      }
    } catch {
      return;
    }
  }

  mkdirSync(target, { recursive: true });
  writeFileSync(join(target, 'package.json'), buildSharedShimPackageJson(), 'utf-8');
  writeFileSync(markerPath, 'edgebase-shared-shim\n', 'utf-8');
  ensureDirectorySymlink(join(source, 'src'), join(target, 'src'));
}

function findWorkspaceRoot(startDir: string): string | null {
  let currentDir = resolve(startDir);

  while (true) {
    if (existsSync(join(currentDir, 'pnpm-workspace.yaml')) || existsSync(join(currentDir, '.git'))) {
      return currentDir;
    }

    const parentDir = dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

function ensureDirectorySymlink(source: string, target: string): void {
  const currentLink = readExistingSymlinkTarget(target);
  if (currentLink === source) return;
  if (currentLink !== null || existsSync(target)) {
    rmSync(target, { recursive: true, force: true });
  }

  symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
}

function readExistingSymlinkTarget(target: string): string | null {
  try {
    if (!lstatSync(target).isSymbolicLink()) {
      return null;
    }
    return resolve(dirname(target), readlinkSync(target));
  } catch {
    return null;
  }
}

function buildSharedShimPackageJson(): string {
  return `${JSON.stringify(
    {
      name: '@edgebase/shared',
      private: true,
      type: 'module',
      main: './src/index.ts',
      types: './src/index.ts',
      exports: {
        '.': {
          types: './src/index.ts',
          import: './src/index.ts',
        },
      },
    },
    null,
    2,
  )}\n`;
}

function buildRuntimeConfigShimContents(injectedEnv?: Record<string, string>): string {
  const normalizedEnv = Object.fromEntries(
    Object.entries(injectedEnv ?? {}).filter(([, value]) => typeof value === 'string'),
  );

  if (Object.keys(normalizedEnv).length === 0) {
    return `// Auto-generated by edgebase CLI. Re-export the user project config with a static path so Wrangler can bundle it.
import config from '../../../../edgebase.config.ts';

export default config;
`;
  }

  return `// Auto-generated by edgebase CLI. Inject local config env before evaluating the user project config.
const injectedEnv = ${JSON.stringify(normalizedEnv, null, 2)} as Record<string, string>;

if (typeof process !== 'undefined' && process?.env) {
  for (const [key, value] of Object.entries(injectedEnv)) {
    if (typeof value === 'string' && process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

const mod = await import('../../../../edgebase.config.ts');
const config = (mod as { default?: unknown }).default ?? mod;

export default config;
`;
}

export function writeRuntimeConfigShim(
  projectDir: string,
  injectedEnv?: Record<string, string>,
): void {
  const shimPath = join(getRuntimeServerSrcDir(projectDir), 'generated-config.ts');
  writeFileSync(
    shimPath,
    buildRuntimeConfigShimContents(injectedEnv),
    'utf-8',
  );
}

function writeRuntimeTestConfigShim(projectDir: string): void {
  const shimPath = join(getRuntimeRoot(projectDir), 'edgebase.test.config.ts');
  const tsConfigPath = join(projectDir, 'edgebase.test.config.ts');
  const jsConfigPath = join(projectDir, 'edgebase.test.config.js');
  const importPath = existsSync(tsConfigPath)
    ? '../../../edgebase.test.config.ts'
    : existsSync(jsConfigPath)
      ? '../../../edgebase.test.config.js'
      : './src/generated-config.ts';

  writeFileSync(
    shimPath,
    `// Auto-generated by edgebase CLI. Keep the runtime test-config import resolvable in scaffolded dev environments.
// If the project does not define a dedicated test config, fall back to the generated runtime config shim.
import config from '${importPath}';

export default config;
`,
    'utf-8',
  );
}
