name: edgebase_flutter
description: EdgeBase Flutter/Dart SDK — client-side auth, database-live, and more.
version: 0.2.5
homepage: https://github.com/edge-base/edgebase/tree/main/packages/sdk/dart/packages/flutter
repository: https://github.com/edge-base/edgebase/tree/main/packages/sdk/dart/packages/flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  edgebase_core: ^0.2.5
  http: ^1.2.0
  js: ^0.7.2
  shared_preferences: ^2.2.0
  web_socket_channel: ^3.0.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.0
  flutter_inappwebview: ^6.0.0
  realtimekit_core: ^0.1.5+1
  realtimekit_core_platform_interface: ^0.1.5
  flutter_webrtc: ^1.4.0

dev_dependencies:
  test: ^1.24.0
  edgebase_admin:
    path: ../admin
  flutter_test:
    sdk: flutter

dependency_overrides:
  edgebase_core:
    path: ../core
