export {
  CURRENT_PLUGIN_API_VERSION,
  defineConfig,
  defineFunction,
  getDbAccess,
  getTableAccess,
  getTableHooks,
  getStorageBucketAccess,
  getStorageHooks,
  getPushAccess,
  getPushHandlers,
  getAuthAccess,
  getAuthHandlers,
  getAuthEnrichHandler,
  getMailHooks,
  getRoomAccess,
  getRoomStateConfig,
  getRoomHooks,
  getRoomHandlers,
  getRoomLifecycleHandlers,
  getRoomActionHandlers,
  getRoomTimerHandlers,
  normalizeFrontendMountPath,
  materializeConfig,
} from './config.js';
export type {
  // ─── Core Config ───
  EdgeBaseConfig,
  FrontendConfig,
  // ─── Database-first (§1,) ───
  DbBlock,
  DbAdminConfig,
  DbProvider,
  DbAccess,
  DbLevelRules,
  DbRuleCtx,
  AdminInstanceDiscovery,
  AdminInstanceDiscoveryContext,
  AdminInstanceDiscoveryOption,
  ManualAdminInstanceDiscovery,
  TableAdminInstanceDiscovery,
  FunctionAdminInstanceDiscovery,
  TableConfig,
  TableAccess,
  TableRules,
  TableHandlers,
  TableHooks,
  // ─── Auth Context ───
  AuthContext,
  // ─── Hook Context ───
  HookCtx,
  // ─── Schema ───
  FieldType,
  SchemaField,
  FkReference,
  IndexConfig,
  MigrationConfig,
  // ─── Auth Config ───
  AuthConfig,
  AuthAccess,
  AuthAccessCtx,
  AuthAccessRule,
  AuthHandlers,
  AuthHandlerHooks,
  EmailOtpConfig,
  MagicLinkConfig,
  MfaConfig,
  OAuthProviderCredentialsConfig,
  OidcProviderCredentialsConfig,
  OAuthProvidersConfig,
  PasskeysConfig,
  PasswordPolicyConfig,
  SmsConfig,
  // ─── Email Config ───
  EmailConfig,
  EmailTemplateOverrides,
  EmailSubjectOverrides,
  MailHooks,
  MailHookCtx,
  MailType,
  SmsHooks,
  SmsHookCtx,
  SmsType,
  // ─── Storage (§5) ───
  StorageConfig,
  StorageBucketConfig,
  StorageBucketAccess,
  StorageBucketRules,
  StorageHandlers,
  StorageHooks,
  StorageHookCtx,
  WriteFileMeta,
  R2FileMeta,
  // ─── CORS / Rate Limiting ───
  CorsConfig,
  RateLimitingConfig,
  // ─── Functions ───
  FunctionsConfig,
  CloudflareConfig,
  FunctionContext,
  FunctionDefinition,
  FunctionTrigger,
  FunctionTriggerType,
  DbTrigger,
  AuthTrigger,
  StorageTrigger,
  ScheduleTrigger,
  HttpTrigger,
  // ─── Plugin ───
  PluginManifest,
  PluginInstance,
  // ─── Service Key ───
  ServiceKeyEntry,
  ServiceKeysConfig,
  ServiceKeyConstraints,
  ScopeString,
  // ─── Captcha ───
  CaptchaConfig,
  // ─── Push ───
  PushConfig,
  PushAccess,
  PushFcmConfig,
  PushHandlers,
  PushHookCtx,
  PushRules,
  PushSendInput,
  PushSendOutput,
  // ─── Database Live ───
  DatabaseLiveConfig,
  // ─── KV / D1 / Vectorize ───
  KvNamespaceConfig,
  KvNamespaceRules,
  D1DatabaseConfig,
  VectorizeConfig,
  // ─── Room v2 ───
  RoomNamespaceConfig,
  RoomAccess,
  RoomRuntimeConfig,
  RoomRuntimeTarget,
  RoomStateConfig,
  RoomHooks,
  RoomMemberHooks,
  RoomStateHooks,
  RoomSignalHooks,
  RoomSessionHooks,
  RoomHandlers,
  RoomLifecycleHandlers,
  RoomCreateHandler,
  RoomJoinHandler,
  RoomLeaveHandler,
  RoomDestroyHandler,
  RoomActionHandlers,
  RoomTimerHandlers,
  RoomSender,
  RoomMemberInfo,
  RoomServerAPI,
  RoomHandlerContext,
  RoomTableProxy,
  RoomDbProxy,
} from './config.js';

export { EdgeBaseError, createErrorResponse, FunctionError, FunctionErrorCode } from './errors.js';
export type { ErrorResponse, FieldError, FunctionErrorCodeType } from './errors.js';

export type { FilterOperator, SortDirection } from './types.js';
