#!/usr/bin/env node

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, parse, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
// Marker file written into every generated export directory so we can safely
// recognize (and overwrite) a prior artifact without recursively deleting an
// arbitrary user directory.
const EXPORT_MARKER = '.edgebase-agent-skills-export';
const config = JSON.parse(
  readFileSync(resolve(__dirname, 'config.json'), 'utf-8'),
);

function parseArgs(argv) {
  const options = {
    outDir: resolve(ROOT, config.distributionDir),
    publicRepo: config.publicRepo,
  };

  for (const arg of argv) {
    if (arg.startsWith('--out-dir=')) {
      const rawOutDir = arg.slice('--out-dir='.length).trim();
      if (rawOutDir.length === 0) {
        throw new Error('--out-dir must not be empty.');
      }
      options.outDir = resolve(ROOT, rawOutDir);
      continue;
    }
    if (arg.startsWith('--public-repo=')) {
      options.publicRepo = arg.slice('--public-repo='.length).trim();
    }
  }

  return options;
}

function withTrailingSep(dir) {
  return dir.endsWith(sep) ? dir : `${dir}${sep}`;
}

function assertSafeOutputDir(outDir) {
  if (outDir === parse(outDir).root) {
    throw new Error('--out-dir must not resolve to the filesystem root.');
  }

  if (outDir === ROOT) {
    throw new Error('--out-dir must not resolve to the repository root.');
  }

  const rootWithSep = withTrailingSep(ROOT);
  const outWithSep = withTrailingSep(outDir);

  // Refuse any ancestor of the repo root (e.g. `--out-dir=..`) — deleting it
  // would wipe the repository (and its parent).
  if (rootWithSep.startsWith(outWithSep)) {
    throw new Error(
      `--out-dir must not be an ancestor of the repository root (${outDir}).`,
    );
  }

  // Anything inside the repository is allowed.
  if (outWithSep.startsWith(rootWithSep)) {
    return;
  }

  // Outside the repository: only proceed if the target does not exist, is an
  // empty directory, or is a previously generated export (has our marker).
  if (!existsSync(outDir)) {
    return;
  }

  if (existsSync(resolve(outDir, EXPORT_MARKER))) {
    return;
  }

  const entries = readdirSync(outDir);
  if (entries.length === 0) {
    return;
  }

  throw new Error(
    `--out-dir (${outDir}) is outside the repository and is a non-empty directory `
      + 'without an EdgeBase export marker. Refusing to recursively delete it. '
      + 'Choose an empty directory, a path inside the repository, or a prior export directory.',
  );
}

function writeRepoReadme(outputDir, publicRepo) {
  const contents = `# EdgeBase Agent Skills

Installable EdgeBase AI skill bundles generated from the main EdgeBase monorepo.

If you reached this repository from search, start with the official AI guide first:

- https://edgebase.fun/docs/getting-started/ai

## Contents

- \`skills/edgebase\` — the single public EdgeBase skill with generated SDK and CLI references

## Install

- Codex: copy \`skills/edgebase\` into \`$CODEX_HOME/skills/edgebase\`
- GitHub-backed skill installers: use the \`${publicRepo}\` repository and install the \`edgebase\` skill from \`skills/edgebase\`

## What This Skill Does

- detects EdgeBase tasks from natural language and repo context
- routes to the narrowest CLI or SDK reference by runtime and trust boundary
- helps agents avoid mixing browser/mobile client code with admin/server-only SDKs

## Source Of Truth

This distribution is generated from:

- \`skills/edgebase/SKILL.md\`
- \`skills/edgebase/agents/openai.yaml\`
- \`skills/edgebase/references/generated/*.md\`
- the leaf \`llms.txt\` files in the main EdgeBase repository

Do not edit the generated files in the published repo by hand. Update the source repo and resync instead.
`;

  writeFileSync(resolve(outputDir, 'README.md'), contents, 'utf-8');
}

function main() {
  const { outDir, publicRepo } = parseArgs(process.argv.slice(2));
  const skillSourceDir = resolve(ROOT, 'skills/edgebase');
  const skillOutDir = resolve(outDir, 'skills/edgebase');
  const licenseSource = resolve(ROOT, 'LICENSE');

  assertSafeOutputDir(outDir);

  if (!existsSync(skillSourceDir)) {
    throw new Error('Missing skills/edgebase source directory.');
  }

  if (!existsSync(licenseSource)) {
    throw new Error('Missing root LICENSE file.');
  }

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(resolve(outDir, 'skills'), { recursive: true });
  writeFileSync(
    resolve(outDir, EXPORT_MARKER),
    'Generated by tools/agent-skill-gen/export.mjs. Safe to delete.\n',
    'utf-8',
  );

  cpSync(skillSourceDir, skillOutDir, { recursive: true });
  cpSync(licenseSource, resolve(outDir, 'LICENSE'));
  writeRepoReadme(outDir, publicRepo);

  console.log(`Exported EdgeBase agent skills to ${relative(ROOT, outDir) || outDir}`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
